# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Explore Colombia
email: info@explorecolombia.com.co
description: > # this means to ignore newlines until "baseurl:"
  Study-abroad programs. Cultural and Educational Tourism.
  For teachers, students, executies, and world travelers.
baseurl: "http://explorecolombia.com.co" # the subpath of your site, e.g. /blog
url: "http://explorecolombia.com.co" # the base hostname & protocol for your site
twitter_username: efragozo
github_username:  ederjosef7@@gmail.com

# Build settings
markdown: kramdown
